---

plugins:
  - import
  - node
  - promise
  - jest

env:
  node: true
  es2020: true
  jest/globals: true

extends:
  - 'standard'
  - 'plugin:import/recommended'
  - 'plugin:node/recommended'
  - 'plugin:promise/recommended'

parserOptions:
  ecmaVersion: 11
  sourceType: module
